"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Plus, Search, MoreHorizontal, Pencil, Trash2, FolderTree } from "lucide-react";
import { cn } from "@/lib/utils";

interface CategoryItem {
  _id: string;
  name: string;
  slug: string;
  productCount: number;
  status: string;
  description?: string;
}

const statusStyles: Record<string, string> = {
  active: "bg-emerald-500/10 text-emerald-500",
  inactive: "bg-gray-500/10 text-gray-500",
};

const statusLabels: Record<string, string> = {
  active: "ใช้งาน",
  inactive: "ปิดใช้งาน",
};

export default function CategoriesPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [categories, setCategories] = useState<CategoryItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");

  useEffect(() => {
    const fetchCategories = async () => {
      setIsLoading(true);
      try {
        const res = await fetch("/api/categories");
        const data = await res.json();
        if (!res.ok) {
          throw new Error(data.error || "ไม่สามารถโหลดหมวดหมู่ได้");
        }
        setCategories(data.categories || []);
      } catch (err) {
        console.error(err);
        setError(err instanceof Error ? err.message : "ไม่สามารถโหลดหมวดหมู่ได้");
      } finally {
        setIsLoading(false);
      }
    };

    fetchCategories();
  }, []);

  const filteredCategories = categories.filter((category) => category.name.toLowerCase().includes(searchQuery.toLowerCase()));

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">หมวดหมู่</h1>
          <p className="text-muted-foreground">จัดหมวดหมู่สินค้าให้เป็นระเบียบ</p>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button>
              <Plus className="mr-2 h-4 w-4" />
              เพิ่มหมวดหมู่
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>เพิ่มหมวดหมู่ใหม่</DialogTitle>
              <DialogDescription>สร้างหมวดหมู่ใหม่เพื่อจัดสินค้าให้เป็นระเบียบ</DialogDescription>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              {error && (
                <div className="rounded-md border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">
                  {error}
                </div>
              )}
              <div className="grid gap-2">
                <Label htmlFor="name">ชื่อหมวดหมู่</Label>
                <Input id="name" value={name} onChange={(e) => setName(e.target.value)} placeholder="ชื่อหมวดหมู่" />
              </div>
              {/* Slug is auto-generated by the backend; hidden from the UI */}
              <div className="grid gap-2">
                <Label htmlFor="description">คำอธิบาย</Label>
                <Textarea id="description" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="คำอธิบายหมวดหมู่" />
              </div>
            </div>
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsDialogOpen(false)}>
                ยกเลิก
              </Button>
                <Button type="button" disabled={isSaving} onClick={async () => {
                setError(null);
                if (!name.trim()) {
                  setError("กรุณากรอกชื่อหมวดหมู่");
                  return;
                }
                setIsSaving(true);
                try {
                  const res = await fetch("/api/categories", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                      body: JSON.stringify({ name: name.trim(), description: description.trim() }),
                  });
                  const data = await res.json();
                  if (!res.ok) {
                    throw new Error(data.error || "ไม่สามารถสร้างหมวดหมู่ได้");
                  }
                  setCategories((prev) => [data, ...prev]);
                  setName("");
                  setDescription("");
                  setIsDialogOpen(false);
                } catch (err) {
                  setError(err instanceof Error ? err.message : "ไม่สามารถสร้างหมวดหมู่ได้");
                } finally {
                  setIsSaving(false);
                }
              }}>
                {isSaving ? "กำลังบันทึก..." : "สร้างหมวดหมู่"}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      {/* Search */}
      <Card>
        <CardContent className="pt-6">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input placeholder="ค้นหาหมวดหมู่..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} className="pl-10" />
          </div>
        </CardContent>
      </Card>

      {/* Categories Grid */}
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {filteredCategories.map((category, i) => (
          <Card key={category._id || category.slug || i} className="relative overflow-hidden">
            <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                  <FolderTree className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <CardTitle className="text-base">{category.name}</CardTitle>
                  <p className="text-xs text-muted-foreground font-mono">/{category.slug}</p>
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon" className="h-8 w-8">
                    <MoreHorizontal className="h-4 w-4" />
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>
                    <Pencil className="mr-2 h-4 w-4" />
                    แก้ไข
                  </DropdownMenuItem>
                  <DropdownMenuItem className="text-destructive">
                    <Trash2 className="mr-2 h-4 w-4" />
                    ลบ
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground mb-4">{category.description}</p>
              <div className="flex items-center justify-between">
                <span className="text-sm">
                  <span className="font-semibold">{category.productCount}</span> สินค้า
                </span>
                <Badge variant="secondary" className={cn(statusStyles[category.status])}>
                  {statusLabels[category.status] || category.status}
                </Badge>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
